server:
  port: 8085

spring:
  application:
    name: treatment-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://PediaLink:PediaLink@pedialink.0d8a5qd.mongodb.net/pedialink?retryWrites=true&w=majority}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    tn.pedialink.treatment: DEBUG
