server:
  port: 8082

spring:
  application:
    name: treatment-monitoring-service
  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      uri: mongodb+srv://PediaLink:PediaLink@pedialink.0d8a5qd.mongodb.net/pedialink?retryWrites=true&w=majority

  datasource:
    url: jdbc:h2:file:./data/treatment-backup;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pedialink

app:
  cors:
    allowed-origins: http://localhost:4200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    tn.pedialink.treatment: DEBUG
    org.springframework.security: INFO
